# Copyright (c) 2018 Intel Corporation, 2021 IBM Corp.
#
# SPDX-License-Identifier: Apache-2.0

FROM quay.io/centos/centos@sha256:6fc587a47e7d92c4ece5c735cb34bdbdce54907c71fea2f0cc55eddb35bb374d
@SET_PROXY@

RUN dnf -y update && \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf -y install \
    diffutils \
    file \
    g++ \
    git \
    protobuf-compiler \
    xz

@INSTALL_RUST@
